name: Tests

on:
  workflow_call:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Run TSC
        run: bun --bun turbo dist

      - name: Run Biome
        run: bun --bun biome check

      - name: Run tests
        run: bun --bun turbo test